= Podman Systemd Image
Jordan Williams <jordan@jwillikers.com>
:experimental:
:icons: font
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:Buildah: https://buildah.io/[Buildah]
:Fedora: https://getfedora.org/[Fedora]
:OpenSSH: https://www.openssh.com/[OpenSSH]
:Podman: https://podman.io/[Podman]
:Systemd: https://systemd.io/[Systemd]

image:https://img.shields.io/github/workflow/status/jwillikers/openssh-server-image/CI/main[GitHub Workflow Status]

A {Systemd}-enabled version of the https://quay.io/repository/containers/podman[containers/podman] image.

== Quick Start

Supported architectures:: `amd64`, `arm32v7`, `arm64v8`

Run {Podman} in a container based off the image with {Podman}.

[source,sh]
----
➜ podman run --rm -it --name podman-systemd quay.io/jwillikers/podman-systemd podman --version
----

== Build

Use {Buildah} to build the image.

. Install the necessary dependencies.
+
[source,sh]
----
➜ sudo dnf -y install git buildah podman
----

. Clone this repository.
+
[source,sh]
----
➜ git -C ~/Projects clone git@github.com:jwillikers/podman-systemd-image.git
----

. Run the shell script.
+
[source,sh]
----
➜ ~/Projects/podman-systemd-image/podman-systemd-image.sh
----

== Contributing

Contributions in the form of issues, feedback, and even pull requests are welcome.
Make sure to adhere to the project's link:CODE_OF_CONDUCT.adoc[Code of Conduct].

== Open Source Software

This project is built on the hard work of countless open source contributors.
Several of these projects are enumerated below.

* https://asciidoctor.org/[Asciidoctor]
* {Buildah}
* {Fedora}
* https://git-scm.com/[Git]
* https://www.linuxfoundation.org/[Linux]
* {OpenSSH}
* {Podman}
* https://www.python.org/[Python]
* https://rouge.jneen.net/[Rouge]
* https://www.ruby-lang.org/en/[Ruby]
* https://systemd.io/[Systemd]

== Code of Conduct

The project's Code of Conduct is available in the link:CODE_OF_CONDUCT.adoc[Code of Conduct] file.

== License

This repository is licensed under the https://www.gnu.org/licenses/gpl-3.0.html[GPLv3], available in the link:LICENSE.adoc[license file].

© 2021 Jordan Williams

== Authors

mailto:{email}[{author}]
